version: 0.2

phases:
  install:
    commands:
      - echo Updating apt packages...
      - apt-get update -y
      - apt-get install -y wget gnupg software-properties-common unzip

      # Install Temurin JDK 21 (Eclipse Adoptium)
      - wget https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.1%2B12/OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz
      - mkdir -p /opt/java/openjdk
      - tar -xzf OpenJDK21U-jdk_x64_linux_hotspot_21.0.1_12.tar.gz -C /opt/java/openjdk
      - export JAVA_HOME=/opt/java/openjdk/jdk-21.0.1+12
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - javac -version

      - echo Installing Maven dependencies...
      - ./mvnw clean install -DskipTests

  build:
    commands:
      - echo Building jar file...
      - ./mvnw package -DskipTests
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - cp Procfile deploy/

artifacts:
  files:
    - deploy/**/*
