version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - ./mvnw clean install -DskipTests

  build:
    commands:
      - echo Building the application...
      - ./mvnw package -DskipTests
      - echo Preparing deploy directory...
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - cp Procfile deploy/

artifacts:
  files:
    - deploy/**
