version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Packaging app...
      - mvn package -DskipTests
      - mkdir -p deploy
      - cp target/*.jar deploy/
      - cp Procfile deploy/
artifacts:
  files:
    - deploy/**
