version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - mvn clean install -DskipTests
  build:
    commands:
      - echo Packaging Spring Boot app...
      - mvn package -DskipTests
artifacts:
  files:
    - target/FantasyScout.jar
    - Procfile
